# ------------------------------------------------------------------------
# Modified from NAFNet (https://github.com/megvii-research/NAFNet)
# ------------------------------------------------------------------------
# general settings
name: AAPM-group-MDPRNet
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: AAPM
    type: PairedImageDataset
    dataroot_gt: ./datasets/train_group2_h/HR_CT_train.lmdb
    dataroot_lq: ./datasets/train_group2_h/LR_CT_train_group2_h.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: AAPM_val
    type: PairedImageDataset
    dataroot_gt: ./datasets/val_18/HR_CT_val.lmdb
    dataroot_lq: ./datasets/val_144/LR_CT_val_144.lmdb
    io_backend:
      type: lmdb


network_g:
  type: MDPRNet
  enc_blk_nums0: [4, 4, 8]
  enc_blk_nums1: [4, 4, 8]
  middle_blk_num0: 0
  middle_blk_num1: 0
  dec_blk_nums0: [2, 2, 2]
  dec_blk_nums1: [2, 2, 2]
  num_cab: 2
  
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 50000
    eta_min: !!float 1e-6

  total_iter: 50000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1.
    reduction: mean
  
  # stage1_opt:
  #   type: PSNRLoss
  #   loss_weight: 1.
  #   reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# angle
angle: 'group_h-MPRNet'